version: '2'
services:
  matchandtrade-web-ui:
    image: rafaelsantosbra/matchandtrade-web-ui:0.0-SNAPSHOT
    container_name: matchandtrade-web-ui
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "80:80"
    volumes:
     - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
     - ./log-ui:/usr/local/apache2/logs
  matchandtrade-web-api:
    image: rafaelsantosbra/matchandtrade-web-api:0.0-SNAPSHOT
    container_name: matchandtrade-web-api
    ports:
     - "8080:8080"
    volumes:
     - ./config:/matchandtrade/config
     - ./database:/matchandtrade/database
     - ./log-api:/matchandtrade/log
     - ./file-storage:/matchandtrade/file-storage
  mocked-oauth-server:
    image: rafaelsantosbra/mocked-oauth-server:0.0-SNAPSHOT
    container_name: mocked-oauth-server
    ports:
      - 8081:8081
